# Generated by Django 2.0 on 2018-01-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='channel_id',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
